### ISSUE TITLE
Article HTMLElement and Node needs improvement

### ISSUE THREAD

**Issue by mistyharsh** [webf-zone/short-js#4]
Article on [HTMLElement and Node](https://short-js.webf.zone/dom/htmlelement-and-node.html) needs polishing:

It is lacking few very important concepts:

1. Context of the article is not established properly. It begins too directly with a image that is not too helpful.
2. Article conclude by saying `HTMLElement` is `Node` but not vice a versa. However, it never explains what is the difference between them.
3. Who and why Node is there! Why they are different!
4. It should have some roots back to XML from where it is coming from.
5. The diagram of **DOM interfaces** is too out of context.
6. Missing some conclusion/usage/consequences section.

**Comment by kumarbhot** [comment]
ok, @mistyharsh, that's pretty harsh, but will make those changes.
